apiVersion: batch/v1
kind: Job
metadata:
  name: jobs_test
spec:
  template:
    metadata:
      name: jobs_test
    spec:
      containers:
      - name: pi
        image: perl
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
