apiVersion: batch/v1
kind: Job
metadata:
  name: jobs1
spec:
  completions: 45
  parallelism: 2
  template:
    metadata:
      name: jobs1
    spec:
      containers:
      - name: job1
        image: ubuntu:14.04
        command: ["sh", "-c",  "echo 'beijing';sleep 5s"]
      restartPolicy: Never
